language: ruby

env:
  - DB=pgsql

services:
  - postgresql

script:
  - bundle exec rspec

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

addons:
  postgresql: "9.5"

sudo: required
